---
name: ARGOCD

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      APP_NAME:
        required: false
        type: string
      APP_ENV:
        required: true
        type: string
      ARGOCD_CONF_DIR:
        required: false
        type: string
        default: .argocd
    secrets:
      GITHUB_TOKEN:
        required: true
      ARGOCD_USER:
        required: true
      ARGOCD_PASS:
        required: true
      ARGOCD_URL:
        required: true

env:
  APP_ENV: "${{ inputs.APP_ENV }}"
  APP_NAME: "${{ inputs.APP_NAME }}"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Short SHA
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        id: sha
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
      - name: argocd login
        uses: clowdhaus/argo-cd-action/@main
        with:
          version: 1.8.4
          command: login
          options: --insecure --grpc-web --username ${{ secrets.ARGOCD_USER }} --password ${{ secrets.ARGOCD_PASS}} ${{ secrets.ARGOCD_URL }}
      - uses: clowdhaus/argo-cd-action/@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APP_NAME: ${{ env.APP_NAME }}
        with:
          command: proj
          options: create pay-loadbay -f ${{ env.ARGOCD_CONF_DIR }}/project-${{ env.APP_ENV }}.y*ml
